# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qGpLQ75Frsfsd0kMCiRD68VYPmimfWIZ
"""

import streamlit as st
import pandas as pd
import plotly.express as px

!pip install streamlit
import streamlit as st
import pandas as pd
import plotly.express as px

# ======================
# PAGE CONFIG
# ======================
st.set_page_config(page_title="AI Farming Assistant", page_icon="🌾", layout="wide")

# White & Green Theme
st.markdown("""
<style>
body { background-color: #FFFFFF; }
.sidebar .sidebar-content { background-color: #e9f7ef !important; }
h1, h2, h3 { color: #1b5e20 !important; }
</style>
""", unsafe_allow_html=True)

# ======================
# LOAD DATA
# ======================
df = pd.read_csv("crop_yield.csv")
df.columns = df.columns.str.strip().str.replace(" ", "_")

# ======================
# TITLE
# ======================
st.title("🌾 AI-Powered Farming Assistant Dashboard")
st.write("Smart analytics for Kerala farmers using crop yield data.")

# ======================
# SIDEBAR FILTERS
# ======================
st.sidebar.header("🔍 Filters")

crop_list = df["Crop"].unique()
state_list = df["State"].unique()
year_list = df["Crop_Year"].unique()

crop_filter = st.sidebar.multiselect("Select Crop", crop_list, default=crop_list[:1])
state_filter = st.sidebar.multiselect("Select State", state_list, default=state_list[:1])
year_range = st.sidebar.slider("Select Year Range",
                               int(df["Crop_Year"].min()), int(df["Crop_Year"].max()),
                               (int(df["Crop_Year"].min()), int(df["Crop_Year"].max())))

filtered = df[
    (df["Crop"].isin(crop_filter)) &
    (df["State"].isin(state_filter)) &
    (df["Crop_Year"].between(year_range[0], year_range[1]))
]

# ======================
# DATA PREVIEW
# ======================
st.subheader("📄 Dataset Preview")
st.dataframe(filtered.head())

# ======================
# SUMMARY
# ======================
st.subheader("📊 Summary Statistics")
st.write(filtered.describe())

# ======================
# YIELD TREND
# ======================
st.subheader("📈 Yield Trend Over Time")
fig1 = px.line(filtered, x="Crop_Year", y="Yield", color="Crop", markers=True)
st.plotly_chart(fig1, width='stretch')

# ======================
# PRODUCTION
# ======================
st.subheader("🏞️ State-wise Production")
fig2 = px.bar(filtered, x="State", y="Production", color="Crop")
st.plotly_chart(fig2, width='stretch')

# ======================
# AREA vs PRODUCTION
# ======================
if "Area" in df.columns:
    st.subheader("🌱 Area vs Production")
    fig3 = px.scatter(filtered, x="Area", y="Production", size="Yield", color="Crop")
    st.plotly_chart(fig3, width='stretch')

st.success("Dashboard Loaded Successfully 🌱🌾")
